version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - PORT=80
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-railway}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${DB_PASS:-password}
      - SMTP_ENABLED=${SMTP_ENABLED:-false}
    volumes:
      - ./pedidos:/app/pedidos
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=railway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: